import React, { useEffect, useState } from 'react';
import { X, ShieldCheck } from 'lucide-react';
import type { User, UserSignatureProfile } from '../../types';
import { apiService } from '../../services/apiService';
import { signatureService, type MySignatureProfile } from '../../features/signature/signatureService';
import { SignatureEditor, type SignatureEditorValue } from '../signature/SignatureEditor';

interface UserSignatureSettingsModalProps { currentUser: User; onClose: () => void; onSaved?: (profile: UserSignatureProfile) => void; }
const isUuid = (id: string) => /^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(id);
const toFrontendProfile = (p: MySignatureProfile): UserSignatureProfile => ({ id: p.id, userId: p.userId, method: p.method, typedName: p.typedName, typedFontKey: p.typedFontKey, drawingData: p.drawingData, signatureAssetId: p.signatureAssetId, sourceImageFilename: p.sourceImageFilename, extractionVersion: p.extractionVersion, isActive: p.isActive, updatedAt: p.updatedAt });
const fontFamily = (key?: string) => key === 'signature_classic' ? 'Georgia, serif' : key === 'signature_elegant' ? '"Brush Script MT", cursive' : key === 'signature_handwritten' ? '"Comic Sans MS", cursive' : 'cursive';
const blobAsDataUrl = (blob: Blob) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error('Unable to read extracted signature.')); reader.readAsDataURL(blob); });

export const UserSignatureSettingsModal: React.FC<UserSignatureSettingsModalProps> = ({ currentUser, onClose, onSaved }) => {
  const supabaseUser = isUuid(currentUser.id);
  const [profile, setProfile] = useState<MySignatureProfile | null>(null); const [editorValue, setEditorValue] = useState<SignatureEditorValue | null>(null); const [uploadedPreviewUrl, setUploadedPreviewUrl] = useState<string | undefined>(); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { let mounted = true; setLoading(true); setUploadedPreviewUrl(undefined); const request = supabaseUser ? signatureService.getMySignatureProfile() : apiService.getUserSignatureProfile(); void request.then(async (raw: any) => { if (!mounted) return; let drawingData = raw?.drawingReference; if (typeof drawingData === 'string') { try { drawingData = JSON.parse(drawingData); } catch { drawingData = undefined; } } const next: MySignatureProfile | null = supabaseUser ? raw : raw ? { id: raw.id, userId: raw.userId, method: raw.method, typedName: raw.typedName, drawingData, signatureAssetId: raw.assetReference, isActive: raw.isActive !== false, updatedAt: raw.updatedAt } : null; setProfile(next); if (supabaseUser && next?.method === 'uploaded') { try { const preview = await signatureService.resolveMySignaturePreview(); if (mounted) setUploadedPreviewUrl(preview); } catch (previewError: any) { if (mounted) setError(previewError.message || 'Unable to load your imported signature preview.'); } } }).catch((err: any) => mounted && setError(err.message || 'Unable to load your signature.')).finally(() => mounted && setLoading(false)); return () => { mounted = false; }; }, [supabaseUser]);
  const beginEdit = () => { setError(null); setMessage(null); if (!profile || profile.method === 'uploaded') setEditorValue({ method: 'typed', typedName: profile?.typedName || currentUser.name || '', typedFontKey: (profile?.typedFontKey as any) || 'signature_default' }); else if (profile.method === 'typed') setEditorValue({ method: 'typed', typedName: profile.typedName || '', typedFontKey: (profile.typedFontKey as any) || 'signature_default' }); else setEditorValue({ method: 'drawn', drawingData: profile.drawingData || { version: 1, strokes: [] } }); setEditing(true); };
  const save = async () => { if (!editorValue) { setError('Add a signature before saving.'); return; } setSaving(true); setError(null); try { let saved: any; if (supabaseUser) { if (editorValue.method === 'uploaded') { const result = await signatureService.saveImportedSignatureProfile(editorValue); saved = result.profile; setUploadedPreviewUrl(result.previewUrl); } else saved = await signatureService.saveMySignatureProfile(editorValue); } else { let assetReference: string | undefined; if (editorValue.method === 'uploaded') { const base64Data = await blobAsDataUrl(editorValue.extractedBlob); const uploaded = await apiService.uploadSignatureAsset({ filename: editorValue.sourceFileName, mimeType: 'image/png', base64Data, attestationAccepted: true }); assetReference = uploaded.url; } saved = await apiService.saveUserSignatureProfile({ method: editorValue.method, typedName: editorValue.method === 'typed' ? editorValue.typedName : undefined, drawingReference: editorValue.method === 'drawn' ? JSON.stringify(editorValue.drawingData) : undefined, assetReference }); } if (saved) { const next = supabaseUser ? saved : { ...profile, ...saved }; setProfile(next as MySignatureProfile); onSaved?.(supabaseUser ? toFrontendProfile(next as MySignatureProfile) : saved); } setEditing(false); setMessage('Signature profile saved successfully.'); } catch (err: any) { setError(err.message || 'Unable to save your signature.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 bg-slate-900/60 flex items-center justify-center p-4"><div className="bg-white rounded-2xl max-w-2xl w-full shadow-2xl border border-slate-200 max-h-[92vh] overflow-y-auto"><div className="px-6 py-4 bg-slate-900 text-white flex items-center justify-between"><div className="flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-indigo-400" /><div><h2 className="text-sm font-extrabold uppercase tracking-wider">My Signature</h2><p className="text-[11px] text-slate-400">Manage your personal report signature</p></div></div><button type="button" onClick={onClose} aria-label="Close"><X className="w-5 h-5" /></button></div><div className="p-6 space-y-4">{loading ? <p className="text-xs text-slate-500">Loading signature…</p> : editing ? <><SignatureEditor value={editorValue || undefined} onChange={setEditorValue} defaultName={currentUser.name} required disabled={saving} /><button type="button" onClick={save} disabled={saving} className="w-full rounded-lg bg-indigo-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save Signature'}</button></> : <><h3 className="text-sm font-bold text-slate-900">Current Signature</h3>{profile ? <div className="rounded-xl border border-slate-200 bg-slate-50 p-5"><p className="text-xs text-slate-500">Method: <strong className="capitalize">{profile.method}</strong></p>{profile.method === 'typed' && <p className="mt-3 text-3xl italic text-indigo-950" style={{ fontFamily: fontFamily(profile.typedFontKey) }}>{profile.typedName}</p>}{profile.method === 'drawn' && <p className="mt-3 text-xs text-slate-600">Drawn signature saved ({profile.drawingData?.strokes?.length || 0} strokes).</p>}{profile.method === 'uploaded' && (uploadedPreviewUrl ? <img src={uploadedPreviewUrl} alt="Imported signature" className="mt-3 max-h-20 w-full object-contain" /> : <p className="mt-3 text-xs text-slate-600">Uploaded signature saved. Preview is available after a fresh import in this session.</p>)}</div> : <p className="text-xs text-slate-500">No signature profile saved yet.</p>}<button type="button" onClick={beginEdit} className="w-full rounded-lg bg-indigo-600 px-4 py-2 text-xs font-bold text-white">Change Signature</button>{message && <p className="text-xs font-semibold text-emerald-700">{message}</p>}</>}{error && <p className="text-xs font-semibold text-rose-600">{error}</p>}</div></div></div>;
};
